### ISSUE TITLE
Dependencies error inside itu-p1203

### ISSUE THREAD

**Issue by Shivansh20128** [uccmisl/godash#8]
Hi, I am trying to build the setup you have explained. I ran the script (on a new VM) given at UCC Mobile and Internet System Lab [MISL](http://cs1dev.ucc.ie/misl/godash2.0/). However, the script gives an error during the installation of dependencies for the repo itu-p1203. Specifically, the error comes with this command -"sudo pip3 install ." after cloning the repo itu-p1203 and moving into the directory.
Here is a screenshot of the error.
Please advise how to resolve this.
Thank You
![image](https://github.com/uccmisl/godash/assets/88429611/809feafd-e15e-486a-8119-dcbc3f90c650)

**Comment by jq5** [comment]
Hi there,

This seems to be a P.1203 issue and not a godash issue.

It seems P.1203 downloads but does not install.


You could try and install P.1203 with:

pip3 install git+https://github.com/itu-p1203/itu-p1203
And then run “pip3 install .” From within the downloaded folder.  And see if this works.


P.1203 may have new requirements since the scripts were made, so double check that all the dependencies are installed.  Check their GitHub here;
https://github.com/itu-p1203/itu-p1203￼
itu-p1203/itu-p1203: ITU-T Rec. P.1203 Implementation
github.com



I can see the error mentioned online in a few places, and one given solution was:

The solution was that there was no empty __init__.py file in the sub-folder tools, only in the super-folder python_library. Adding a file __init__.py into this folder made it work.

But this must be within P.1203 and not in godash.

Hope this helps

Best wishes,

J

Dr. Jason Quinlan

Lecturer 

School of Computer Science and Information Technology | Room G.72 Western Gateway Building | University College Cork | T12 XF62
☎ +353 21 4205987 | ✉ ***@***.*** ***@***.***> | ***@***.***

￼ ￼ ￼ ￼ ￼
